# Generated by Django 5.0.2 on 2024-03-18 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_rename_staddress_store_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='area',
        ),
    ]
