# Generated by Django 5.0.2 on 2024-03-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0002_city_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='pincode',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
