# Generated by Django 5.0.2 on 2024-03-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0003_area_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='pincode',
            field=models.IntegerField(max_length=6),
        ),
    ]
