# Generated by Django 5.0.2 on 2024-03-17 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0004_alter_area_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
